### PR TITLE
Typescript init and Bills, Banks and Beneficiaries working

### PR DESCRIPTION
**Pull request by iamsethsamuel**
I have set up typescript and added type to Banks, Bill and Beneficiaries. They are all working with their appropriate types. Please let me know what you think so I should know how to process ASAP. Thanks

### CODE REVIEW

**Comment by iamsethsamuel** [comment]
Is anyone seeing this or should I just abandon the project

**Comment by orimdominic** [comment]
@iamsethsamuel Nice work!

The changes in this PR are much. Very much.
You are requesting to merge your work to a live product. It needs to be tested and reviewed to make sure that it does not break anything (I'm not implying that it does).
Another thing is that a project such as converting a codebase from JS to TS needs to have a plan and follow a step-wise process.

I don't think that there's anything bad about your work. The maintainers are probably very busy.
:+1:

**Comment by iamsethsamuel** [comment]
> @iamsethsamuel Nice work!
> 
> The changes in this PR are much. Very much. You are requesting to merge your work to a live product. It needs to be tested and reviewed to make sure that it does not break anything (I'm not implying that it does). Another thing is that a project such as converting a codebase from JS to TS needs to have a plan and follow a step-wise process. Did you read the [contributions guide](https://github.com/Flutterwave/Node/blob/master/CONTRIBUTING.md)? +1

Yeah, it's really big. I was thinking that you guys can create a branch for the transition. https://github.com/Flutterwave/Node/issues/69#issuecomment-1261523498 plan is perfect. So if you can create the branch, I will close this PR and recreate it on that branch and we continue from there. And when all is tested, that branch can be merged with the main branch

**Comment by Corvus97** [comment]
Hi @iamsethsamuel,

Please raise these changes against the dev branch. Based on the volume of changes made, it would take us some time to review and test for unintended changes, but rest assured, we would work on it.

We appreciate you for making contributions to the library. I'd be in touch.

**Pull request closed without merging**
